version: "3.3"

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "1234"
      WORDPRESS_DB_NAME: wordpress
    restart: always
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes/
      - ./wp-content/plugins:/var/www/html/wp-content/plugins/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      enguillem:
        ipv4_address: "10.56.1.21"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      enguillem:
        ipv4_address: "10.56.1.20"
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    depends_on:
      - wordpress
    networks:
      enguillem:
        ipv4_address: "10.56.1.22"
networks:
  enguillem:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"